### ISSUE TITLE
Latest release v0.223.0 broke our build

### ISSUE THREAD

**Issue by rmax** [databricks/setup-cli#116]
Just in case anyone else is affected, we had to stick to v0.222.0 installer to have the CLI working as expected.

Otherwise it failed without any error message when running import-dir command.

**Comment by pietern** [comment]
Thanks for reporting. What exactly errored?

We didn't work on `import-dir`, so I'm surprised.

**Comment by pietern** [comment]
Looks like a problem snuck into error reporting in general.

This should not affect working commands and only cause error outputs to remain hidden.

**Comment by rmax** [comment]
Added some details here: https://github.com/databricks/cli/issues/1563

**Comment by pietern** [comment]
Version v0.223.1 is now released with a fix. It is available through this repository (setup-cli) and Homebrew.
