### ISSUE TITLE
add support for arm/aarch64 CPU architecture

### ISSUE THREAD

**Issue by taihang-lei** [databricks/setup-cli#27]
For linux machines, `arm` CPU architecture always roles out `aarch64` [when running `uname -m`](https://github.com/databricks/setup-cli/blob/main/install.sh#L32-L50), could you please add support for that?

**Comment by pietern** [comment]
@taihang-lei Thanks for reporting. Could you check if the fix I linked fixes the issue for you?

**Comment by taihang-lei** [comment]
Thanks for your quick correspondence, it works as thought.
